### PR TITLE
Increased State Length to 75 and decreased set Interval to Matic Block time

### LINKED ISSUE #106: Increased State Length to 75 and decreased set Interval to Matic Block time
Currently the state length and set Interval time is set according to the goerli Blockchain. And it does not work properly with Matic Chain testnet.
Hence we need to change the state length and set interval according to Matic testnet

### PR DESCRIPTION
**Pull request by adi44**
Currently the state length and Matic Block time was as per the goerli Chain. Changed value of State Length and set Interval according to Matic testnet

Fixes #106

### CODE REVIEW

**Review by SkandaBhat — APPROVED** [review]

File: api.js [hunk 1]
```diff
@@ -489,8 +489,8 @@ async function getState() {
 async function getDelayedState() {
   let blockNumber = await web3.eth.getBlockNumber();
   // its too late to make the tx
-  if (blockNumber % 10 > 4 || blockNumber % 10 < 1) return -1;
-  let state = Math.floor(blockNumber / 10);
+  if (blockNumber % 75 > 4 || blockNumber % 75 < 1) return -1;
```
Comment (ashish10677) [inline api.js:492]: Shouldn't the buffer period for every state also increase?
It was `(blockNumber % 10 > 4 || blockNumber % 10 < 1)` when we were calculating mod 10
But since we are calculating mod 75 now, >4 and <1 would be a very small buffer period.

**Review by ashish10677 — CHANGES_REQUESTED** [review]

File: api.js (hunk 1 above)
Comment (ashish10677) [reply api.js:492]: @SkandaBhat I would like to know your thoughts too.

**Review by ashish10677 — APPROVED** [review]
